version: 2

project_name: gokub

builds:
  - id: gokub
    main: ./cmd/gokub
    binary: gokub
    env:
      - CGO_ENABLED=0

    goos:
      - darwin
      - linux

    goarch:
      - amd64
      - arm64

    ldflags:
      - >-
        -s -w
        -X github.com/ongyoo/gokub.Version={{ .Version }}
        -X github.com/ongyoo/gokub.Repository={{ .Env.GITHUB_REPOSITORY }}
        -X github.com/ongyoo/gokub.Commit={{ .Commit }}
        -X github.com/ongyoo/gokub.BuildDate={{ .Date }}

archives:
  - id: release
    ids:
      - gokub

    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}Darwin{{ else }}Linux{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else }}arm64{{ end }}

    formats:
      - tar.gz

    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
